credentials:
  usernames:
    Rafael:
      email: rafaelcpaes@unifei.edu.br
      name: Rafael Coelho Paes
      password: '123' # To be replaced with hashed password
    Jeremias:
      email: jeremias@unifei.edu.br
      name: Jeremias Barbosa Machado
      password: '123' # To be replaced with hashed password
cookie:
  expiry_days: 0
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com